apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.email: infra@example.org
spec:
  description: AppProject for ArgoCD-specific applications.
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  # must be able to get all git repos because of the Applications pointing to other repos
  sourceRepos:
    - http://scmm-scm-manager.default.svc.cluster.local/scm/repo/argocd/argocd
    - http://scmm-scm-manager.default.svc.cluster.local/scm/repo/argocd/cluster-resources
    - http://scmm-scm-manager.default.svc.cluster.local/scm/repo/argocd/example-apps
  # Allow applications from all namespaces to use this project for now.
  sourceNamespaces:
    - '*'